name: app_quan_trac_dt
description: Ứng dụng Quan Trắc đa module

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0  # dùng cho cả mobile và desktop
  path: ^1.9.0
  dropdown_button2: ^2.3.9
  two_dimensional_scrollables: ^0.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
