name: app_quan_trac_dt
description: Ứng dụng Quan Trắc đa module

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # DB
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  # UI
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  # file/image picker cho desktop
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
