name: app_quan_trac_dt
description: "App quan trắc môi trường"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6

flutter:
  uses-material-design: true

  assets:
    - assets/app_quan_trac_data.sqlite
